dist: jammy
language: python
python:
  - 3.11
install:
  - pip install -r requirements.txt
  - gem install webrick
before_script:
  - cd ebdjango
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - cd ..
script:
  - black .
  - flake8 .
  - cd ebdjango
  - coverage run --source=polls manage.py test
  - cd ..
after_script:
  - curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "ebdjango"
  env: "django-env"
  bucket_name: $AWS_BUCKET
  on:
    repo: MJ3128/swe1-app
    branch: main
