language: python

python:
  - 3.9-dev

install:
  - pip install -r requirements.txt

before_script:
  - cd ebdjango
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - cd ..

script:
  - black --check .
  - flake8 .
  - coverage run --source=ebdjango_swe1_app,polls manage.py test

after_script:
  - coveralls
